### ISSUE TITLE
warns before installing and then don't work

### ISSUE THREAD

**Issue by fczuardi** [joe1chen/nodebb-plugin-sso-tumblr#1]
after installation and activation, clicking on the tumblr item of the admin menu gives a not found error:

> /api/admin/plugins/sso-tumblr Não Encontrado
> 
> not-found

**Comment by fczuardi** [comment]
Ok, I've digged up a little and patched some files, I think I got it fixed when I compared the files https://github.com/joe1chen/nodebb-plugin-sso-tumblr/blob/master/library.js with https://github.com/julianlam/nodebb-plugin-sso-twitter/blob/master/library.js the twitter sso-plugin works with nodeBB 0.6.1 and the sso-tumblr did not. My guess is that the init function has different parameters (maybe some API change after 0.5.0? I don't know, can you confirm it @julianlam ?)

Here is what I changed:

``` javascript
        //Tumblr.init = function(app, middleware, controllers, callback) {
        Tumblr.init = function(data, callback) {
                var app = data.router,
                    middleware = data.middleware;

```

Am I on the right track?

**Comment by fczuardi** [comment]
Oh, I see that you've fixed on https://github.com/joe1chen/nodebb-plugin-sso-tumblr/commit/8d73cbf2f6c3234e7710a3e19a0bcb189181da7b in November, but that version is not what npm is bringing… strange

**Comment by fczuardi** [comment]
I just tried removing my `node_modules/nodebb-plugin-sso-tumblr` folder and then `npm install nodebb-plugin-sso-tumblr@0.2.0`

It gave me an error:

```
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
npm ERR! Error: version not found: nodebb-plugin-sso-tumblr@0.2.0
```

Maybe you dind't publish it to npm yet?

Anyways, using `npm install joe1chen/nodebb-plugin-sso-tumblr` did the trick :)

Feel free to close this bug as invalid or fixed since the bug is with installations through npm and not your source code.

**Comment by yeelan0319** [comment]
Thanks @fczuardi. I encountered the same problem for another module for linkedin SSO and I acutally end up substituted the library.js file to make everything work.

**Comment by julianlam** [comment]
Yes, seems like @joe1chen just needs to `npm publish` this up to the npm repository

**Comment by dogomedia** [comment]
Whoops, looks like I didn't ```npm publish``` like @julianlam mentioned.  It should be fixed now.

**Comment by joe1chen** [comment]
Whoops, looks like I didn't `npm publish` like @julianlam mentioned. It should be fixed now.
